### ISSUE TITLE
Structure packing attribute problems

### ISSUE THREAD

**Issue by rsaxvc** [vangdfang/libcutter#5]
An Alexis contacted me over email to say:

[ 7%] Building CXX object lib/CMakeFiles/cutter.dir/device_c.cpp.o
/home/macbookpro/Downloads/libcutter-master/lib/device_c.cpp:34:23: error: expected ‘(’ before ‘**packed**’
struct **attribute**( **packed** ) lmc_command
^

Any idea why we used **packed** instead of packed for the attribute? I've also asked Alexis for the compiler and version used - maybe our build environments defined **packed** ? It still works on Debian with GCC 4.7.2.
